blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/sadhakaai/VikrAI/discussions/categories/feature-requests
    about: Please use GitHub Discussions for suggesting ideas and features
  - name: VikrAI Community
    url: https://discord.gg/vikrai
    about: The official VikrAI Discord community
  - name: Documentation
    url: https://docs.vikrai.com
    about: Official VikrAI Documentation
